// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzQmfR1Sr7saucQddeYzjoO2BOMBCAgEI',
    appId: '1:896599078796:android:5ac4fe3cdfdfd8d0dd88a9',
    messagingSenderId: '896599078796',
    projectId: 'stiko-ad8dd',
    storageBucket: 'stiko-ad8dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUi2pdsNOJSWm__C9JdrlD3FRkqNCFEio',
    appId: '1:896599078796:ios:e5fc727fe5ef2fabdd88a9',
    messagingSenderId: '896599078796',
    projectId: 'stiko-ad8dd',
    storageBucket: 'stiko-ad8dd.firebasestorage.app',
    iosBundleId: 'io.github.sondahyun.stiko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUi2pdsNOJSWm__C9JdrlD3FRkqNCFEio',
    appId: '1:896599078796:ios:e5fc727fe5ef2fabdd88a9',
    messagingSenderId: '896599078796',
    projectId: 'stiko-ad8dd',
    storageBucket: 'stiko-ad8dd.firebasestorage.app',
    iosBundleId: 'io.github.sondahyun.stiko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvDQWJC0nSYU-kNGML_oWI_HZCT4y_aSw',
    appId: '1:896599078796:web:b5a9633350b6feafdd88a9',
    messagingSenderId: '896599078796',
    projectId: 'stiko-ad8dd',
    authDomain: 'stiko-ad8dd.firebaseapp.com',
    storageBucket: 'stiko-ad8dd.firebasestorage.app',
  );
}
